Repository kirill-oleynik/ToDoLists_internship, pull requests merged in 2021-04, with the labels that each got.

#10 Refactoring
  .gitignore
  Gemfile
  Gemfile.lock
  app/concepts/api/v1/auth/operation/sign_up.rb
  app/services/jwt_session/build.rb
  app/services/jwt_session_builder.rb
  config/credentials.yml.enc
  config/initializers/jwt_sessions.rb
  spec/services/jwt_session/build_spec.rb
Labels: Ready For Review

#11 Authentication
  app/concepts/api/v1/auth/contract/refresh_token.rb
  app/concepts/api/v1/auth/contract/sign_in.rb
  app/concepts/api/v1/auth/contract/sign_out.rb
  app/concepts/api/v1/auth/operation/refresh_session.rb
  app/concepts/api/v1/auth/operation/sign_in.rb
  app/concepts/api/v1/auth/operation/sign_out.rb
  app/concepts/api/v1/auth/operation/sign_up.rb
  app/concepts/application_operation.rb
  app/controllers/api/v1/accounts/registrations_controller.rb
  app/controllers/api/v1/api_controller.rb
  app/services/jwt_session/create.rb
  app/services/jwt_session/destroy.rb
  app/services/jwt_session/refresh.rb
  config/routes.rb
  spec/concepts/api/v1/auth/contract/refresh_token_spec.rb
  spec/concepts/api/v1/auth/contract/sign_in_spec.rb
  spec/concepts/api/v1/auth/contract/sign_out_spec.rb
  spec/concepts/api/v1/auth/operation/refresh_session_spec.rb
  spec/concepts/api/v1/auth/operation/sign_in_spec.rb
  spec/concepts/api/v1/auth/operation/sign_out_spec.rb
  spec/concepts/api/v1/auth/operation/sign_up_spec.rb
  spec/requests/api/v1/registrations/sign_up_spec.rb
  spec/requests/api/v1/registrations_spec.rb
  spec/requests/graphql/mutations/user/sign_up_spec.rb
  spec/requests/users/create_request_spec.rb
  spec/services/jwt_session/build_spec.rb
  spec/services/jwt_session/create_spec.rb
  spec/services/jwt_session/destroy_spec.rb
  spec/services/jwt_session/refresh_spec.rb
  spec/support/api/schemas/auth/failure/all_params_invalid.json
  spec/support/api/schemas/auth/failure/email_invalid.json
  spec/support/api/schemas/auth/failure/password_confirmation_invalid.json
  spec/support/api/schemas/auth/failure/password_invalid.json
  spec/support/api/schemas/auth/failure/sign_up.json
  spec/support/api/schemas/auth/failure/username_invalid.json
  spec/support/api/schemas/auth/success/auth_tokens.json
  spec/support/api/schemas/auth/success/sign_up.json
Labels: reviewed

#12 Feature/sign in refresh out
  .rubocop.yml
  app/concepts/api/v1/auth/contract/refresh_token.rb
  app/concepts/api/v1/auth/operation/refresh_session.rb
  app/concepts/api/v1/auth/operation/sign_in.rb
  app/concepts/api/v1/auth/operation/sign_out.rb
  app/controllers/api/v1/accounts/accounts_controller.rb
  app/controllers/api/v1/accounts/registrations_controller.rb
  app/controllers/api/v1/accounts/sessions_controller.rb
  app/controllers/api/v1/api_controller.rb
  spec/concepts/api/v1/auth/operation/refresh_session_spec.rb
  spec/concepts/api/v1/auth/operation/sign_in_spec.rb
  spec/concepts/api/v1/auth/operation/sign_out_spec.rb
  spec/rails_helper.rb
  spec/requests/api/v1/registrations/sign_up_spec.rb
  spec/requests/api/v1/registrations_spec.rb
  spec/requests/api/v1/sessions/referesh_session_spec.rb
  spec/requests/api/v1/sessions/sign_in_spec.rb
  spec/requests/api/v1/sessions/sign_out_spec.rb
  spec/support/request_helpers.rb
Labels: Ready For Review

#13 Refactore RefreshSession & SignOut endpoints
  app/concepts/api/v1/auth/operation/refresh_session.rb
  app/concepts/api/v1/auth/operation/sign_out.rb
  app/controllers/api/v1/accounts/accounts_controller.rb
  app/controllers/api/v1/accounts/sessions_controller.rb
  app/services/jwt_session/refresh.rb
  config/initializers/jwt_sessions.rb
  spec/concepts/api/v1/auth/operation/sign_out_spec.rb
  spec/rails_helper.rb
  spec/requests/api/v1/sessions/referesh_session_spec.rb
  spec/requests/api/v1/sessions/sign_out_spec.rb
  spec/services/jwt_session/refresh_spec.rb
Labels: Ready For Review

#14 Send confirmation email after user been created
  Gemfile
  Gemfile.lock
  app/concepts/api/v1/auth/operation/sign_up.rb
  app/mailers/application_mailer.rb
  app/mailers/user_mailer.rb
  app/views/user_mailer/cignup_confirmation.html.erb
  app/views/user_mailer/cignup_confirmation.text.erb
  config/application.rb
  config/environments/development.rb
  config/initializers/sidekiq.rb
  config/locales/en.yml
Labels: WIP
